[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "omnivggt"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "torch",
    "torchvision",
    "Pillow",
    "opencv-python",
    "scipy",
    "einops",
    "safetensors",
    "trimesh",
    "matplotlib",
    "imageio",
    "tqdm",
    "requests",
    "onnxruntime",
    "huggingface_hub",
    "evo",
    "mmengine",
    "transformers",
    "accelerate",
    "wandb",
    "diffusers",
    "joblib",
    "decord",
    "iopath",
    "tensorboard",
    "hydra-core",
    "omegaconf",
    "pydantic==2.10.6"
]

[tool.hatch.build.targets.wheel]
packages = ["omnivggt"]
